### exercicio aula 16/07

In [11]:
import pandas as pd

### importando dados

In [19]:
url = "dataset/Morador.csv"

In [20]:
pd.read_csv(url)

                                                    morador_id;domicilio_id;idade;genero;grau_instrucao;atividade_morador;possui_habilitacao;portador_necessidades_especiais;setor_atividade_empresa_privada;setor_atividade_empresa_publica;fexp_morador
1;3;60 a 69 anos;Masculino;Ensino Fundamental I...                                               6286
2;3;50 a 59 anos;Feminino;Ensino Fundamental In...                                               6286
3;4;40 a 49 anos;Masculino;Ensino Fundamental I...                                               6147
4;4;18 a 19 anos;Feminino;Ensino Superior Incom...                                               6147
5;4;10 a 14 anos;Masculino;Ensino Fundamental I...                                               6147
...                                                                                               ...
74842;345422;0 a 4 anos;Masculino;Analfabeto;Nã...                                               8228
74843;345423;Mais de 80 anos;Masculino;Pós-Grad...                                               4953
74844;345423;70 a 79 anos;Feminino;Ensino Super...                                               4953
74845;345423;30 a 39 anos;Masculino;Ensino Supe...                                               4953
74846;345424;Mais de 80 anos;Masculino;Pós-Grad...                                               2705

[61358 rows x 1 columns]

In [22]:
url = "dataset/Morador.csv"
pd.read_csv(url,sep=';')

,morador_id,domicilio_id,idade,genero,grau_instrucao,atividade_morador,possui_habilitacao,portador_necessidades_especiais,setor_atividade_empresa_privada,setor_atividade_empresa_publica,fexp_morador
0,1,3,60 a 69 anos,Masculino,Ensino Fundamental Incompleto,Aposentado/Pensionista,Possui,Outros,NaN,NaN,"35,6286"
1,2,3,50 a 59 anos,Feminino,Ensino Fundamental Incompleto,Outros,Não Possui,Não Se Aplica,NaN,NaN,"35,6286"
2,3,4,40 a 49 anos,Masculino,Ensino Fundamental Incompleto,Profissional Liberal,Possui,Não Se Aplica,NaN,NaN,"32,6147"
3,4,4,18 a 19 anos,Feminino,Ensino Superior Incompleto,Estudante Regular,Possui,Não Se Aplica,NaN,NaN,"32,6147"
4,5,4,10 a 14 anos,Masculino,Ensino Fundamental Incompleto,Estudante Regular,Não Possui,Não Se Aplica,NaN,NaN,"32,6147"
...,...,...,...,...,...,...,...,...,...,...,...
61353,74842,345422,0 a 4 anos,Masculino,Analfabeto,Não Tem Atividade,Não Possui,Não Se Aplica,NaN,NaN,"57,8228"
61354,74843,345423,Mais de 80 anos,Masculino,Pós-Graduação/Mestrado/Doutorado,Aposentado/Pensionista,Possui,Não Se Aplica,NaN,NaN,"33,4953"
61355,74844,345423,70 a 79 anos,Feminino,Ensino Superior Completo,Aposentado/Pensionista,Não Possui,Não Se Aplica,NaN,NaN,"33,4953"
61356,74845,345423,30 a 39 anos,Masculino,Ensino Superior Completo,Funcionário Público,Possui,Não Se Aplica,NaN,Administração Federal,"33,4953"
61357,74846,345424,Mais de 80 anos,Masculino,Pós-Graduação/Mestrado/Doutorado,Aposentado/Pensionista,Possui,Não Se Aplica,NaN,NaN,"35,2705"

In [3]:
dados = pd.read_csv(url,sep=';')
dados
type(dados)

NameError: name 'pd' is not defined

In [1]:

dados.head()

NameError: name 'dados' is not defined